---
- name: 'Copy Database deployment Manifest files'
  template:
    src: 'database-deployment.j2'
    dest: '/home/{{ database_app_name }}_deployment.yaml'

- name: 'Copy Database Service Manifest files'
  template:
    src: 'database-service.j2'
    dest: '/home/{{ database_app_name }}_service.yaml'

- name: 'Create a Deployment for Database {{ database_app_name }}'
  kubernetes.core.k8s:
    state: present
    src: '/home/{{ database_app_name }}_deployment.yaml'

- name: 'Create a Service for Database {{ database_app_name }}'
  kubernetes.core.k8s:
    state: present
    src: '/home/{{ database_app_name }}_service.yaml'